# 工作流名称
name: Deploy Jekyll site to Pages

# 触发条件
on:
  # 在推送到默认分支时触发
  push:
    branches: ["main"]
  # 允许手动触发
  workflow_dispatch:

# 权限设置
permissions:
  contents: read
  pages: write
  id-token: write

# 并发设置，确保只有一个部署在进行
concurrency:
  group: "pages"
  cancel-in-progress: false

# 任务定义
jobs:
  # 构建任务
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 设置 Ruby 环境
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      # 设置页面
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      # 4. 构建站点
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      # 5. 上传构建产物
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  # 部署任务
  deploy:
    # 依赖构建任务
    needs: build
    
    # 部署环境
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-22.04
    
    steps:
      # 1. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
